setup inputs weights and bias before we develop functions and build everything out

In [1]:
inputs = [1, 2 ,3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

In [2]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

In [3]:
output

4.8

In [4]:
#notes: every input has its own weight but every neuron gets its own bias. There are 3 3 and 1 here

In [5]:
# what if we add an input? (would need to add weight) we do this to code above so there will be one example

In [6]:
#what about 3 neurons with 4 inputs 
#what is a neuron? Rosenblatt, history, derived math, various takes etc.

In [7]:
#3 neurons
inputs = [1, 2 ,3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]


bias1 = 2.0
bias2 = 3
bias3 = 0.5

In [8]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
        inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
        inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]

In [9]:
output

[4.8, 1.21, 2.385]

In [10]:
#from here we will convert the above beginning understanding of a neuron and 

In [11]:
inputs = [1, 2 ,3, 2.5]

# weights1 = [0.2, 0.8, -0.5, 1.0]
# weights2 = [0.5, -0.91, 0.26, -0.5]
# weights3 = [-0.26, -0.27, 0.17, 0.87]

#list of lists
weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]


# bias1 = 2.0
# bias2 = 3
# bias3 = 0.5

biases = [2, 3, 0.5]

layer_outputs = [] #output current layer
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 #output of given neuron 
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
    
layer_outputs

[4.8, 1.21, 2.385]

In [12]:
# now we will get into dot product, shape errors, and other
#shape, at each dimension, what is the size? 

In [13]:
import numpy as np

In [14]:
inputs = [1, 2 ,3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(inputs, weights) + bias
output

4.8

In [15]:
# above we put inputs before weights. It does not matter in this case but will later. 

In [18]:
inputs = [1, 2 ,3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]


biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
output

array([4.8  , 1.21 , 2.385])

In [17]:
#questions:
# how many neurons are in our current model? how do we know?
# how does this relate to n x p matrix multiplication that fall from the 
# axioms of linear algebra?

In [21]:
#batching
#using too many samples in batch at once can lead to overfitting while only showing very small amount
#is too small to see greater context of D
#using CPU vs GPU running calculations..CPU core is for much harder calculations than needed
#for matrix multiplication

In [26]:
inputs = [[1, 2 ,3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0], 
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]


biases = [2, 3, 0.5]

#second layer
weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

#convert weights to numpy array so we can transpose
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [27]:
#this manual construction of layers can get out of control quickly. We can make it 
#an object.
#..
#typically, this is where we could use our previously trained model, a particular set 
# of unique weights and biases that successfully perform task T with respect to a goal.


In [37]:
np.random.seed(0)

#input data (3 samples)
X = [[1, 2 ,3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4, 5)    
layer2 = Layer_Dense(5, 2)    

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [38]:
# we have weights and biases but we have not explored the necessity of an activation function.

# Activation functions

In [44]:
# rectified linear, softmax, other
#step functions can be used.
#sigmoid function is often used.
#rectified linear (granular like sigmoid, but faster than sig)
#why use activation functions at all?
#related to the fact that we are dealing with linear/nonlinear functions. ReLU..
#ReLU 
# ouput = activation(weights*inputs + bias)
 %pip install nnfs

Note: you may need to restart the kernel to use updated packages.


In [56]:
#np.random.seed(0) going to use nnfs package for this part
import nnfs

import nnfs
from nnfs.datasets import spiral_data

def create_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points) #radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

import matplotlib.pyplot as plt

print("here")
X, y = create_data(100, 3)

nnfs.init()

#input data (3 samples)
X = [[1, 2 ,3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

# inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
# output = []

# for i in inputs:
# #     if i >0:
# #         output.append(i)
# #     elif i <= 0:
# #         output.append(0)
# # or we could write the same this as:
#        output.append(max(0, i)) 
# print(output)

X, y = spiral_data(100, 3)


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Activation_ReLU: #rectified linear unit
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)
        

layer1 = Layer_Dense(2, 5)    
#layer2 = Layer_Dense(5, 2)   
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)

activation1.forward(layer1.output)
print(activation1.output)

# #print(layer1.output)
# layer2.forward(layer1.output)
# print(layer2.output)

here
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]
